### ISSUE TITLE
Register doesn't work with multiple notifications

### ISSUE THREAD

**Issue by CrazyCoder** [snaka/ruby_gntp#6]
@notifications.each do |notification| ... doesn't separate multiple notifications with \r\n, therefore register method will work with just one notification, but will fail with 2 or more.

**Comment by snaka** [comment]
Fixed:
Commit 43f5e34e7a5992db620166a5284899ea9ba7f087 to snaka's ruby_gntp - GitHub
http://github.com/snaka/ruby_gntp/commit/43f5e34e7a5992db620166a5284899ea9ba7f087
